version: '3.4'

services:

  gateway:

    container_name: GatewayAPI

    image: ${DOCKER_REGISTRY-}gateway

    build:
      context: .
      dockerfile: src/Service/Gateway/Dockerfile

    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=5000

    ports:
        - "5000:5000"

  account:

    container_name: Account

    image: ${DOCKER_REGISTRY-}account

    build:
      context: .
      dockerfile: src/Service/Microservices/Account/AccountAPI/Dockerfile

    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=5001

    ports:
        - "5001:5001"
