version: '3.4'

networks:
    connection:
        driver: bridge

services:

  #--------------------------------------------------------

  gateway:

    container_name: GatewayAPI

    image: ${DOCKER_REGISTRY-}gateway

    build:
      context: .
      dockerfile: src/Service/Gateway/Dockerfile

    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=5000

    ports:
        - "5000:5000"
        
    networks:
        - connection

  #--------------------------------------------------------

  account:

    container_name: Account

    image: ${DOCKER_REGISTRY-}account

    build:
      context: .
      dockerfile: src/Service/Microservices/Account/AccountAPI/Dockerfile

    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=5001

    ports:
        - "5001:5001"
  
    networks:
        - connection
    
    depends_on:
        - accountDatabase
        
  #--------------------------------------------------------

  accountDatabase:

    container_name: AccountDatabase

    image: postgres:latest

    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Frostwert234Z
        POSTGRES_DB: AccountDatabase
        PGPORT: 5011
  
    ports:
        - "5011:5011"

    networks:
        - connection
    
    volumes:
        - account_data:/var/lib/postgresql/data
        
  #--------------------------------------------------------

volumes:
    account_data: